### ISSUE TITLE
Script doesn't work anymore

### ISSUE THREAD

**Issue by gaetan1903** [sskender/pornhub-api#6]
The script doesn't work ,

**Comment by gaetan1903** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd044964820>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

**Comment by gaetan1903** [comment]
My IP is blocked by Pornhub.

How to use ipv6 Ip ?

**Comment by sskender** [comment]
I am sorry for such a late response.

Script isn't actively maintained, but feel free to create a PR.

If your IP is blocked, you can use proxy as it is documented in README. In general, your IP depends on your ISP and you can not tweak it, except using proxy or vpn, but that has nothing to do with this repository.
