### ISSUE TITLE
This is not working when I try to obtain stars or even search a video through keywords

### ISSUE THREAD

**Issue by SurajMeena** [sskender/pornhub-api#8]
`
Traceback (most recent call last):
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api_test.py", line 4, in <module>
    for star in client.getStars(10):
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/pornhub/stars.py", line 80, in getStars
    for possible_star in self._scrapLiStars(self._loadStarsPage(page)):
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/pornhub/stars.py", line 12, in _loadStarsPage
    r = requests.get(BASE_URL + PORNSTARS_URL, params=payload, headers=HEADERS, proxies=self.ProxyDictionary)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/suraj/miniconda3/envs/python3.8_env/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`
Getting this error.....What can be done to resolve the issue ?

**Comment by sskender** [comment]
This look like you are unable to open a connection with the website. There is nothing wrong with the Python script.

Can you access the website through your browser? Did you try accessing with VPN or proxy?

**Comment by SurajMeena** [comment]
> This look like you are unable to open a connection with the website. There is nothing wrong with the Python script.
> 
> Can you access the website through your browser? Did you try accessing with VPN or proxy?

yeah I am able to use it after retrying for 2-3 times. I understand why the issue persists
I had another doubt in it's usage how can we use proxy and keywords in client together ?

**Comment by SurajMeena** [comment]
Also can you help me in pointing out from where can I get a valid proxy and port to feed into client ?

**Comment by sskender** [comment]
You should be able to do it like this:
`client = pornhub.PornHub("5.135.164.72", 3128, keywords)`

Or like this, to be more precise:
`client = pornhub.PornHub(ProxyIP="5.135.164.72", ProxyPort=3128, keywords=["word1", "word2"])`

Be careful, proxy IP and port are stated here only for example and do not represent a real server. You have to find yourself a real proxy server and use its settings. Simple Google search like `free proxy servers` can lead you to this website https://fossbytes.com/free-proxy-list/

I do not use proxy servers much, so I won't be much of a help, but I hope you find a working one.

**Comment by SurajMeena** [comment]
thankyou so much.....you can close the issue now and it is a kind request to update readme to include the parameters that can passed in it.
